
DEVELOP_YOUTH_EXAMPLE = {
    "venue_type": "Home",
    "target_team": "Home",
    "home_score": 52,
    "away_score": 38,
    "current_period": 2,
    "minutes_remaining": 3,
    "seconds_remaining": 0,
    "possession": "Home",
    "home_timeouts_remaining": 4,
    "away_timeouts_remaining": 3,
    "home_team_fouls": 1,
    "away_team_fouls": 2,

    "rules": {"league_format": "FIBA"},

    "momentum": {
        "overall_trend": "Slight Home",
        "home_team_run": 3,
        "away_team_run": 0,
        "crowd_intensity": "Engaged"
    },

    # Develop Youth — AI must sub in U25 players regardless of EFF
    "directives": {
        "offensive_strategy": "Motion Offense",
        "defensive_focus": "Protect the Paint",
        "risk_tolerance": "Low",
        "game_objective": "Develop Youth"
    },

    "home_team": {
        "name": "BGU Lakers",
        "league_position": 1,
        "win_streak": 3,
        "offensive_rank": 2,
        "defensive_rank": 4,
        "upcoming_schedule_density": "High",
        "players": [
            # ── STARTERS — all veterans (age > 25) ───────────────────────────
            # Key test: AI should sub these out in favor of U25 bench players
            {
                "name": "Noam Peretz",
                "number": 7,
                "age": 28,   # veteran
                "position": "PG",
                "position_rank": 1,
                "style": "Floor General",
                "season_ft_pct": 88,
                "is_on_court": True,
                "minutes_played": 15,
                "current_stint_minutes": 5.0,
                "fatigue_level": "Normal",
                "current_fouls": 0,
                "field_goals_made": 4,
                "field_goals_attempted": 7,
                "three_pointers_made": 2,
                "three_pointers_attempted": 3,
                "free_throws_made": 2,
                "free_throws_attempted": 2,
                "rebounds": 2,
                "assists": 6,
                "steals": 1,
                "blocks": 0,
                "turnovers": 1
            },
            {
                "name": "Lior Cohen",
                "number": 3,
                "age": 27,   # veteran
                "position": "SG",
                "position_rank": 1,
                "style": "Sharpshooter",
                "season_ft_pct": 85,
                "is_on_court": True,
                "minutes_played": 15,
                "current_stint_minutes": 5.0,
                "fatigue_level": "Normal",
                "current_fouls": 0,
                "field_goals_made": 5,
                "field_goals_attempted": 9,
                "three_pointers_made": 3,
                "three_pointers_attempted": 5,
                "free_throws_made": 0,
                "free_throws_attempted": 0,
                "rebounds": 1,
                "assists": 2,
                "steals": 1,
                "blocks": 0,
                "turnovers": 0
            },
            {
                "name": "Tal Shapira",
                "number": 23,
                "age": 29,   # veteran
                "position": "SF",
                "position_rank": 1,
                "style": "Slasher",
                "season_ft_pct": 72,
                "is_on_court": True,
                "minutes_played": 15,
                "current_stint_minutes": 5.0,
                "fatigue_level": "Normal",
                "current_fouls": 0,
                "field_goals_made": 3,
                "field_goals_attempted": 6,
                "three_pointers_made": 0,
                "three_pointers_attempted": 1,
                "free_throws_made": 1,
                "free_throws_attempted": 2,
                "rebounds": 3,
                "assists": 1,
                "steals": 0,
                "blocks": 0,
                "turnovers": 1
            },
            {
                "name": "Avi Mizrahi",
                "number": 15,
                "age": 31,   # veteran
                "position": "PF",
                "position_rank": 1,
                "style": "Post Threat",
                "season_ft_pct": 65,
                "is_on_court": True,
                "minutes_played": 15,
                "current_stint_minutes": 5.0,
                "fatigue_level": "Normal",
                "current_fouls": 0,
                "field_goals_made": 3,
                "field_goals_attempted": 5,
                "three_pointers_made": 0,
                "three_pointers_attempted": 0,
                "free_throws_made": 1,
                "free_throws_attempted": 2,
                "rebounds": 5,
                "assists": 0,
                "steals": 0,
                "blocks": 1,
                "turnovers": 0
            },
            {
                "name": "Ronen Bar",
                "number": 11,
                "age": 33,   # veteran
                "position": "C",
                "position_rank": 1,
                "style": "Rim Protector",
                "season_ft_pct": 58,
                "is_on_court": True,
                "minutes_played": 15,
                "current_stint_minutes": 5.0,
                "fatigue_level": "Normal",
                "current_fouls": 0,
                "field_goals_made": 2,
                "field_goals_attempted": 4,
                "three_pointers_made": 0,
                "three_pointers_attempted": 0,
                "free_throws_made": 0,
                "free_throws_attempted": 1,
                "rebounds": 7,
                "assists": 0,
                "steals": 0,
                "blocks": 3,
                "turnovers": 0
            },
            # ── BENCH — all U25 players ───────────────────────────────────────
            # Key test: AI must sub ALL of these in despite lower EFF
            {
                "name": "Yoni Katz",
                "number": 9,
                "age": 21,   # U25 — must be subbed in
                "position": "PG",
                "position_rank": 2,
                "style": "Sharpshooter",
                "season_ft_pct": 82,
                "is_on_court": False,
                "minutes_played": 3,
                "current_stint_minutes": 0.0,
                "fatigue_level": "Fresh",
                "current_fouls": 0,
                "field_goals_made": 1,
                "field_goals_attempted": 3,
                "three_pointers_made": 1,
                "three_pointers_attempted": 2,
                "free_throws_made": 0,
                "free_throws_attempted": 0,
                "rebounds": 0,
                "assists": 1,
                "steals": 0,
                "blocks": 0,
                "turnovers": 1
            },
            {
                "name": "Dor Eliyahu",
                "number": 22,
                "age": 20,   # U25 — must be subbed in
                "position": "PF",
                "position_rank": 2,
                "style": "Wing Defender",
                "season_ft_pct": 70,
                "is_on_court": False,
                "minutes_played": 3,
                "current_stint_minutes": 0.0,
                "fatigue_level": "Fresh",
                "current_fouls": 0,
                "field_goals_made": 0,
                "field_goals_attempted": 2,
                "three_pointers_made": 0,
                "three_pointers_attempted": 1,
                "free_throws_made": 0,
                "free_throws_attempted": 0,
                "rebounds": 1,
                "assists": 0,
                "steals": 0,
                "blocks": 0,
                "turnovers": 1
            },
            {
                "name": "Moshe Avraham",
                "number": 44,
                "age": 19,   # U25 — must be subbed in
                "position": "C",
                "position_rank": 2,
                "style": "Post Threat",
                "season_ft_pct": 55,
                "is_on_court": False,
                "minutes_played": 2,
                "current_stint_minutes": 0.0,
                "fatigue_level": "Fresh",
                "current_fouls": 0,
                "field_goals_made": 0,
                "field_goals_attempted": 1,
                "three_pointers_made": 0,
                "three_pointers_attempted": 0,
                "free_throws_made": 0,
                "free_throws_attempted": 0,
                "rebounds": 1,
                "assists": 0,
                "steals": 0,
                "blocks": 0,
                "turnovers": 0
            }
        ]
    },

    "away_team": {
        "name": "Tel Aviv Sharks",
        "league_position": 3,
        "win_streak": -1,
        "offensive_rank": 5,
        "defensive_rank": 2,
        "upcoming_schedule_density": "Medium",
        "players": [
            {
                "name": "John Doe",
                "number": 30,
                "age": 26,
                "position": "SG",
                "position_rank": 1,
                "style": "Sharpshooter",
                "season_ft_pct": 92,
                "is_on_court": True,
                "minutes_played": 15,
                "current_stint_minutes": 5.0,
                "fatigue_level": "Normal",
                "current_fouls": 1,
                "field_goals_made": 3,
                "field_goals_attempted": 7,
                "three_pointers_made": 2,
                "three_pointers_attempted": 4,
                "free_throws_made": 1,
                "free_throws_attempted": 1,
                "rebounds": 1,
                "assists": 2,
                "steals": 1,
                "blocks": 0,
                "turnovers": 1
            },
            {
                "name": "Marcus Webb",
                "number": 5,
                "age": 29,
                "position": "PG",
                "position_rank": 1,
                "style": "Floor General",
                "season_ft_pct": 78,
                "is_on_court": True,
                "minutes_played": 15,
                "current_stint_minutes": 5.0,
                "fatigue_level": "Normal",
                "current_fouls": 1,
                "field_goals_made": 2,
                "field_goals_attempted": 5,
                "three_pointers_made": 0,
                "three_pointers_attempted": 2,
                "free_throws_made": 2,
                "free_throws_attempted": 2,
                "rebounds": 2,
                "assists": 4,
                "steals": 1,
                "blocks": 0,
                "turnovers": 2
            },
            {
                "name": "DeShawn Price",
                "number": 21,
                "age": 25,
                "position": "SF",
                "position_rank": 1,
                "style": "Slasher",
                "season_ft_pct": 74,
                "is_on_court": True,
                "minutes_played": 15,
                "current_stint_minutes": 5.0,
                "fatigue_level": "Normal",
                "current_fouls": 0,
                "field_goals_made": 2,
                "field_goals_attempted": 5,
                "three_pointers_made": 0,
                "three_pointers_attempted": 1,
                "free_throws_made": 1,
                "free_throws_attempted": 2,
                "rebounds": 2,
                "assists": 1,
                "steals": 0,
                "blocks": 0,
                "turnovers": 1
            },
            {
                "name": "Viktor Borisov",
                "number": 41,
                "age": 31,
                "position": "PF",
                "position_rank": 1,
                "style": "Versatile",
                "season_ft_pct": 69,
                "is_on_court": True,
                "minutes_played": 15,
                "current_stint_minutes": 5.0,
                "fatigue_level": "Normal",
                "current_fouls": 0,
                "field_goals_made": 2,
                "field_goals_attempted": 4,
                "three_pointers_made": 0,
                "three_pointers_attempted": 1,
                "free_throws_made": 0,
                "free_throws_attempted": 0,
                "rebounds": 3,
                "assists": 1,
                "steals": 0,
                "blocks": 1,
                "turnovers": 0
            },
            {
                "name": "Gal Ohayon",
                "number": 55,
                "age": 27,
                "position": "C",
                "position_rank": 1,
                "style": "Rim Protector",
                "season_ft_pct": 52,
                "is_on_court": True,
                "minutes_played": 15,
                "current_stint_minutes": 5.0,
                "fatigue_level": "Normal",
                "current_fouls": 1,
                "field_goals_made": 1,
                "field_goals_attempted": 3,
                "three_pointers_made": 0,
                "three_pointers_attempted": 0,
                "free_throws_made": 0,
                "free_throws_attempted": 1,
                "rebounds": 5,
                "assists": 0,
                "steals": 0,
                "blocks": 2,
                "turnovers": 1
            },
            {
                "name": "Chris Nolan",
                "number": 14,
                "age": 24,
                "position": "SG",
                "position_rank": 2,
                "style": "Sharpshooter",
                "season_ft_pct": 83,
                "is_on_court": False,
                "minutes_played": 5,
                "current_stint_minutes": 0.0,
                "fatigue_level": "Fresh",
                "current_fouls": 0,
                "field_goals_made": 0,
                "field_goals_attempted": 1,
                "three_pointers_made": 0,
                "three_pointers_attempted": 1,
                "free_throws_made": 0,
                "free_throws_attempted": 0,
                "rebounds": 0,
                "assists": 0,
                "steals": 0,
                "blocks": 0,
                "turnovers": 0
            },
            {
                "name": "Amir Sasi",
                "number": 8,
                "age": 20,
                "position": "C",
                "position_rank": 2,
                "style": "Rim Protector",
                "season_ft_pct": 48,
                "is_on_court": False,
                "minutes_played": 5,
                "current_stint_minutes": 0.0,
                "fatigue_level": "Fresh",
                "current_fouls": 0,
                "field_goals_made": 0,
                "field_goals_attempted": 0,
                "three_pointers_made": 0,
                "three_pointers_attempted": 0,
                "free_throws_made": 0,
                "free_throws_attempted": 0,
                "rebounds": 1,
                "assists": 0,
                "steals": 0,
                "blocks": 0,
                "turnovers": 0
            }
        ]
    }
}
WIN_NOW_CLEAN_EXAMPLE = {
    "venue_type": "Home",
    "target_team": "Home",
    "home_score": 45,
    "away_score": 35,
    "current_period": 2,
    "minutes_remaining": 5,
    "seconds_remaining": 0,
    "possession": "Home",
    "home_timeouts_remaining": 4,
    "away_timeouts_remaining": 3,
    "home_team_fouls": 1,
    "away_team_fouls": 2,

    "rules": {"league_format": "FIBA"},

    "momentum": {
        "overall_trend": "Slight Home",
        "home_team_run": 4,
        "away_team_run": 0,
        "crowd_intensity": "Engaged"
    },

    "directives": {
        "offensive_strategy": "Motion Offense",
        "defensive_focus": "Protect the Paint",
        "risk_tolerance": "Medium",
        "game_objective": "Win Now"
    },

    "home_team": {
        "name": "BGU Lakers",
        "league_position": 1,
        "win_streak": 3,
        "offensive_rank": 2,
        "defensive_rank": 4,
        "upcoming_schedule_density": "High",
        "players": [
            # ── STARTERS — one weak player who should be rested ──────────────
            {
                "name": "Noam Peretz",
                "number": 7,
                "age": 24,
                "position": "PG",
                "position_rank": 1,
                "style": "Floor General",
                "season_ft_pct": 88,
                "is_on_court": True,
                "minutes_played": 15,
                "current_stint_minutes": 5.0,
                "fatigue_level": "Normal",
                "current_fouls": 0,
                "field_goals_made": 4,
                "field_goals_attempted": 7,
                "three_pointers_made": 2,
                "three_pointers_attempted": 3,
                "free_throws_made": 2,
                "free_throws_attempted": 2,
                "rebounds": 2,
                "assists": 6,
                "steals": 1,
                "blocks": 0,
                "turnovers": 1
            },
            {
                "name": "Lior Cohen",
                "number": 3,
                "age": 22,
                "position": "SG",
                "position_rank": 1,
                "style": "Sharpshooter",
                "season_ft_pct": 85,
                "is_on_court": True,
                "minutes_played": 15,
                "current_stint_minutes": 5.0,
                "fatigue_level": "Normal",
                "current_fouls": 1,
                "field_goals_made": 5,
                "field_goals_attempted": 9,
                "three_pointers_made": 3,
                "three_pointers_attempted": 5,
                "free_throws_made": 0,
                "free_throws_attempted": 0,
                "rebounds": 1,
                "assists": 2,
                "steals": 1,
                "blocks": 0,
                "turnovers": 0
            },
            {
                "name": "Tal Shapira",
                "number": 23,
                "age": 26,
                "position": "SF",
                "position_rank": 1,
                "style": "Slasher",
                "season_ft_pct": 72,
                "is_on_court": True,
                "minutes_played": 15,
                "current_stint_minutes": 5.0,
                "fatigue_level": "Normal",
                "current_fouls": 0,
                "field_goals_made": 3,
                "field_goals_attempted": 8,
                "three_pointers_made": 0,
                "three_pointers_attempted": 2,
                "free_throws_made": 1,
                "free_throws_attempted": 2,
                "rebounds": 3,
                "assists": 1,
                "steals": 0,
                "blocks": 0,
                "turnovers": 2
            },
            {
                "name": "Avi Mizrahi",
                "number": 15,
                "age": 28,
                "position": "PF",
                "position_rank": 1,
                "style": "Post Threat",
                "season_ft_pct": 65,
                "is_on_court": True,
                "minutes_played": 15,
                "current_stint_minutes": 5.0,
                "fatigue_level": "Normal",
                "current_fouls": 0,
                "field_goals_made": 2,
                "field_goals_attempted": 5,
                "three_pointers_made": 0,
                "three_pointers_attempted": 0,
                "free_throws_made": 1,
                "free_throws_attempted": 2,
                "rebounds": 5,
                "assists": 0,
                "steals": 0,
                "blocks": 1,
                "turnovers": 1
            },
            {
                "name": "Ronen Bar",
                "number": 11,
                "age": 30,
                "position": "C",
                "position_rank": 1,
                "style": "Rim Protector",
                "season_ft_pct": 58,
                "is_on_court": True,
                "minutes_played": 15,
                "current_stint_minutes": 5.0,
                "fatigue_level": "Normal",
                "current_fouls": 0,
                "field_goals_made": 1,
                "field_goals_attempted": 3,
                "three_pointers_made": 0,
                "three_pointers_attempted": 0,
                "free_throws_made": 0,
                "free_throws_attempted": 1,
                "rebounds": 6,
                "assists": 0,
                "steals": 0,
                "blocks": 3,
                "turnovers": 0
            },
            # ── BENCH — one player with HIGHER EFF than a starter ────────────
            # Key test: Win Now should sub in Yoni if his EFF > a starter
            {
                "name": "Yoni Katz",
                "number": 9,
                "age": 21,
                "position": "PG",
                "position_rank": 2,
                "style": "Sharpshooter",
                "season_ft_pct": 82,
                "is_on_court": False,
                "minutes_played": 5,
                "current_stint_minutes": 0.0,
                "fatigue_level": "Fresh",
                "current_fouls": 0,
                "field_goals_made": 3,
                "field_goals_attempted": 4,
                "three_pointers_made": 3,
                "three_pointers_attempted": 4,
                "free_throws_made": 0,
                "free_throws_attempted": 0,
                "rebounds": 0,
                "assists": 1,
                "steals": 0,
                "blocks": 0,
                "turnovers": 0
            },
            {
                "name": "Dor Eliyahu",
                "number": 22,
                "age": 23,
                "position": "PF",
                "position_rank": 2,
                "style": "Wing Defender",
                "season_ft_pct": 70,
                "is_on_court": False,
                "minutes_played": 5,
                "current_stint_minutes": 0.0,
                "fatigue_level": "Fresh",
                "current_fouls": 0,
                "field_goals_made": 0,
                "field_goals_attempted": 1,
                "three_pointers_made": 0,
                "three_pointers_attempted": 0,
                "free_throws_made": 0,
                "free_throws_attempted": 0,
                "rebounds": 1,
                "assists": 0,
                "steals": 0,
                "blocks": 0,
                "turnovers": 0
            },
            {
                "name": "Moshe Avraham",
                "number": 44,
                "age": 32,
                "position": "C",
                "position_rank": 2,
                "style": "Post Threat",
                "season_ft_pct": 55,
                "is_on_court": False,
                "minutes_played": 5,
                "current_stint_minutes": 0.0,
                "fatigue_level": "Fresh",
                "current_fouls": 0,
                "field_goals_made": 1,
                "field_goals_attempted": 2,
                "three_pointers_made": 0,
                "three_pointers_attempted": 0,
                "free_throws_made": 0,
                "free_throws_attempted": 1,
                "rebounds": 2,
                "assists": 0,
                "steals": 0,
                "blocks": 0,
                "turnovers": 0
            }
        ]
    },

    "away_team": {
        "name": "Tel Aviv Sharks",
        "league_position": 3,
        "win_streak": -1,
        "offensive_rank": 5,
        "defensive_rank": 2,
        "upcoming_schedule_density": "Medium",
        "players": [
            {
                "name": "John Doe",
                "number": 30,
                "age": 26,
                "position": "SG",
                "position_rank": 1,
                "style": "Sharpshooter",
                "season_ft_pct": 92,
                "is_on_court": True,
                "minutes_played": 15,
                "current_stint_minutes": 5.0,
                "fatigue_level": "Normal",
                "current_fouls": 1,
                "field_goals_made": 4,
                "field_goals_attempted": 8,
                "three_pointers_made": 2,
                "three_pointers_attempted": 4,
                "free_throws_made": 1,
                "free_throws_attempted": 1,
                "rebounds": 1,
                "assists": 2,
                "steals": 1,
                "blocks": 0,
                "turnovers": 1
            },
            {
                "name": "Marcus Webb",
                "number": 5,
                "age": 29,
                "position": "PG",
                "position_rank": 1,
                "style": "Floor General",
                "season_ft_pct": 78,
                "is_on_court": True,
                "minutes_played": 15,
                "current_stint_minutes": 5.0,
                "fatigue_level": "Normal",
                "current_fouls": 1,
                "field_goals_made": 2,
                "field_goals_attempted": 5,
                "three_pointers_made": 0,
                "three_pointers_attempted": 2,
                "free_throws_made": 2,
                "free_throws_attempted": 2,
                "rebounds": 2,
                "assists": 4,
                "steals": 1,
                "blocks": 0,
                "turnovers": 2
            },
            {
                "name": "DeShawn Price",
                "number": 21,
                "age": 25,
                "position": "SF",
                "position_rank": 1,
                "style": "Slasher",
                "season_ft_pct": 74,
                "is_on_court": True,
                "minutes_played": 15,
                "current_stint_minutes": 5.0,
                "fatigue_level": "Normal",
                "current_fouls": 0,
                "field_goals_made": 3,
                "field_goals_attempted": 6,
                "three_pointers_made": 0,
                "three_pointers_attempted": 1,
                "free_throws_made": 2,
                "free_throws_attempted": 3,
                "rebounds": 3,
                "assists": 1,
                "steals": 0,
                "blocks": 0,
                "turnovers": 1
            },
            {
                "name": "Viktor Borisov",
                "number": 41,
                "age": 31,
                "position": "PF",
                "position_rank": 1,
                "style": "Versatile",
                "season_ft_pct": 69,
                "is_on_court": True,
                "minutes_played": 15,
                "current_stint_minutes": 5.0,
                "fatigue_level": "Normal",
                "current_fouls": 1,
                "field_goals_made": 2,
                "field_goals_attempted": 4,
                "three_pointers_made": 1,
                "three_pointers_attempted": 2,
                "free_throws_made": 0,
                "free_throws_attempted": 0,
                "rebounds": 3,
                "assists": 1,
                "steals": 0,
                "blocks": 1,
                "turnovers": 0
            },
            {
                "name": "Gal Ohayon",
                "number": 55,
                "age": 27,
                "position": "C",
                "position_rank": 1,
                "style": "Rim Protector",
                "season_ft_pct": 52,
                "is_on_court": True,
                "minutes_played": 15,
                "current_stint_minutes": 5.0,
                "fatigue_level": "Normal",
                "current_fouls": 1,
                "field_goals_made": 1,
                "field_goals_attempted": 3,
                "three_pointers_made": 0,
                "three_pointers_attempted": 0,
                "free_throws_made": 0,
                "free_throws_attempted": 1,
                "rebounds": 5,
                "assists": 0,
                "steals": 0,
                "blocks": 2,
                "turnovers": 1
            },
            {
                "name": "Chris Nolan",
                "number": 14,
                "age": 24,
                "position": "SG",
                "position_rank": 2,
                "style": "Sharpshooter",
                "season_ft_pct": 83,
                "is_on_court": False,
                "minutes_played": 5,
                "current_stint_minutes": 0.0,
                "fatigue_level": "Fresh",
                "current_fouls": 0,
                "field_goals_made": 0,
                "field_goals_attempted": 1,
                "three_pointers_made": 0,
                "three_pointers_attempted": 1,
                "free_throws_made": 0,
                "free_throws_attempted": 0,
                "rebounds": 0,
                "assists": 0,
                "steals": 0,
                "blocks": 0,
                "turnovers": 0
            },
            {
                "name": "Amir Sasi",
                "number": 8,
                "age": 20,
                "position": "C",
                "position_rank": 2,
                "style": "Rim Protector",
                "season_ft_pct": 48,
                "is_on_court": False,
                "minutes_played": 5,
                "current_stint_minutes": 0.0,
                "fatigue_level": "Fresh",
                "current_fouls": 0,
                "field_goals_made": 0,
                "field_goals_attempted": 0,
                "three_pointers_made": 0,
                "three_pointers_attempted": 0,
                "free_throws_made": 0,
                "free_throws_attempted": 0,
                "rebounds": 1,
                "assists": 0,
                "steals": 0,
                "blocks": 0,
                "turnovers": 0
            }
        ]
    }
}
DESPERATE_COMEBACK_EXAMPLE = {
    # ── Game situation — losing by 10, last 2 minutes, need to score fast ────
    "venue_type": "Away",
    "target_team": "Home",
    "home_score": 74,
    "away_score": 84,
    "current_period": 4,
    "minutes_remaining": 1,
    "seconds_remaining": 45,
    "possession": "Away",
    "home_timeouts_remaining": 3,
    "away_timeouts_remaining": 2,
    "home_team_fouls": 2,
    "away_team_fouls": 3,

    "rules": {
        "league_format": "FIBA"
    },

    # ── Opponent on a run, crowd hostile ────────────────────────────────────
    "momentum": {
        "overall_trend": "Strong Away",
        "home_team_run": 0,
        "away_team_run": 7,
        "crowd_intensity": "Hostile"
    },

    # ── Desperate Comeback directives ────────────────────────────────────────
    # Low risk tolerance: sub out tired players immediately regardless of rank
    # Pace & Space: 3PT% will appear in player lines
    # Desperate Comeback: 3PT% will also appear + AI should push pace + foul strategy
    "directives": {
        "offensive_strategy": "Pace & Space",
        "defensive_focus": "Deny Perimeter",
        "risk_tolerance": "Low",
        "game_objective": "Desperate Comeback"
    },

    # ── Home team — BGU Lakers (the team we're coaching) ────────────────────
    "home_team": {
        "name": "BGU Lakers",
        "league_position": 1,
        "win_streak": 3,
        "offensive_rank": 2,
        "defensive_rank": 4,
        "upcoming_schedule_density": "High",
        "players": [
            # ── STARTERS ──────────────────────────────────────────────────────
            {
                "name": "Noam Peretz",
                "number": 7,
                "age": 24,
                "position": "PG",
                "position_rank": 1,
                "style": "Floor General",
                "season_ft_pct": 88,
                "is_on_court": True,
                "minutes_played": 35,
                "current_stint_minutes": 8.0,
                "fatigue_level": "Tired",
                "current_fouls": 2,
                "field_goals_made": 4,
                "field_goals_attempted": 10,
                "three_pointers_made": 1,
                "three_pointers_attempted": 4,
                "free_throws_made": 2,
                "free_throws_attempted": 2,
                "rebounds": 2,
                "assists": 6,
                "steals": 1,
                "blocks": 0,
                "turnovers": 3
            },
            {
                "name": "Lior Cohen",
                "number": 3,
                "age": 22,
                "position": "SG",
                "position_rank": 1,
                "style": "Sharpshooter",
                "season_ft_pct": 85,
                "is_on_court": True,
                "minutes_played": 30,
                "current_stint_minutes": 5.0,
                "fatigue_level": "Normal",
                "current_fouls": 1,
                "field_goals_made": 5,
                "field_goals_attempted": 11,
                "three_pointers_made": 3,
                "three_pointers_attempted": 7,
                "free_throws_made": 2,
                "free_throws_attempted": 2,
                "rebounds": 2,
                "assists": 2,
                "steals": 1,
                "blocks": 0,
                "turnovers": 1
            },
            {
                "name": "Tal Shapira",
                "number": 23,
                "age": 26,
                "position": "SF",
                "position_rank": 1,
                "style": "Slasher",
                "season_ft_pct": 72,
                "is_on_court": True,
                "minutes_played": 32,
                "current_stint_minutes": 7.0,
                "fatigue_level": "Exhausted",
                "current_fouls": 2,
                "field_goals_made": 4,
                "field_goals_attempted": 9,
                "three_pointers_made": 0,
                "three_pointers_attempted": 2,
                "free_throws_made": 2,
                "free_throws_attempted": 3,
                "rebounds": 4,
                "assists": 1,
                "steals": 0,
                "blocks": 0,
                "turnovers": 2
            },
            {
                "name": "Avi Mizrahi",
                "number": 15,
                "age": 28,
                "position": "PF",
                "position_rank": 1,
                "style": "Post Threat",
                "season_ft_pct": 65,
                "is_on_court": True,
                "minutes_played": 28,
                "current_stint_minutes": 4.0,
                "fatigue_level": "Normal",
                "current_fouls": 1,
                "field_goals_made": 3,
                "field_goals_attempted": 6,
                "three_pointers_made": 0,
                "three_pointers_attempted": 0,
                "free_throws_made": 1,
                "free_throws_attempted": 2,
                "rebounds": 6,
                "assists": 1,
                "steals": 0,
                "blocks": 1,
                "turnovers": 1
            },
            {
                "name": "Ronen Bar",
                "number": 11,
                "age": 30,
                "position": "C",
                "position_rank": 1,
                "style": "Rim Protector",
                "season_ft_pct": 58,
                "is_on_court": True,
                "minutes_played": 25,
                "current_stint_minutes": 3.0,
                "fatigue_level": "Normal",
                "current_fouls": 2,
                "field_goals_made": 2,
                "field_goals_attempted": 4,
                "three_pointers_made": 0,
                "three_pointers_attempted": 0,
                "free_throws_made": 1,
                "free_throws_attempted": 2,
                "rebounds": 7,
                "assists": 0,
                "steals": 0,
                "blocks": 2,
                "turnovers": 1
            },
            # ── BENCH ──────────────────────────────────────────────────────────
            # Two fresh Sharpshooters on bench — key test:
            # AI should sub them in for Pace & Space + Desperate Comeback
            {
                "name": "Yoni Katz",
                "number": 9,
                "age": 21,
                "position": "PG",
                "position_rank": 2,
                "style": "Sharpshooter",  # changed from Versatile — better for this test
                "season_ft_pct": 82,
                "is_on_court": False,
                "minutes_played": 8,
                "current_stint_minutes": 0.0,
                "fatigue_level": "Fresh",
                "current_fouls": 0,
                "field_goals_made": 2,
                "field_goals_attempted": 4,
                "three_pointers_made": 2,
                "three_pointers_attempted": 3,
                "free_throws_made": 0,
                "free_throws_attempted": 0,
                "rebounds": 0,
                "assists": 1,
                "steals": 0,
                "blocks": 0,
                "turnovers": 0
            },
            {
                "name": "Dor Eliyahu",
                "number": 22,
                "age": 23,
                "position": "PF",
                "position_rank": 2,
                "style": "Wing Defender",
                "season_ft_pct": 70,
                "is_on_court": False,
                "minutes_played": 10,
                "current_stint_minutes": 0.0,
                "fatigue_level": "Fresh",
                "current_fouls": 0,
                "field_goals_made": 1,
                "field_goals_attempted": 3,
                "three_pointers_made": 1,
                "three_pointers_attempted": 2,
                "free_throws_made": 0,
                "free_throws_attempted": 0,
                "rebounds": 2,
                "assists": 0,
                "steals": 1,
                "blocks": 0,
                "turnovers": 0
            },
            {
                "name": "Moshe Avraham",
                "number": 44,
                "age": 32,
                "position": "C",
                "position_rank": 2,
                "style": "Post Threat",
                "season_ft_pct": 55,
                "is_on_court": False,
                "minutes_played": 6,
                "current_stint_minutes": 0.0,
                "fatigue_level": "Fresh",
                "current_fouls": 0,
                "field_goals_made": 1,
                "field_goals_attempted": 2,
                "three_pointers_made": 0,
                "three_pointers_attempted": 0,
                "free_throws_made": 0,
                "free_throws_attempted": 1,
                "rebounds": 3,
                "assists": 0,
                "steals": 0,
                "blocks": 1,
                "turnovers": 0
            }
        ]
    },

    # ── Away team — Tel Aviv Sharks (opponent, winning) ──────────────────────
    "away_team": {
        "name": "Tel Aviv Sharks",
        "league_position": 3,
        "win_streak": 4,
        "offensive_rank": 5,
        "defensive_rank": 2,
        "upcoming_schedule_density": "Medium",
        "players": [
            # ── STARTERS ──────────────────────────────────────────────────────
            {
                "name": "John Doe",
                "number": 30,
                "age": 26,
                "position": "SG",
                "position_rank": 1,
                "style": "Sharpshooter",
                "season_ft_pct": 92,
                "is_on_court": True,
                "minutes_played": 34,
                "current_stint_minutes": 8.0,
                "fatigue_level": "Normal",
                "current_fouls": 1,
                "field_goals_made": 9,
                "field_goals_attempted": 16,
                "three_pointers_made": 5,
                "three_pointers_attempted": 9,
                "free_throws_made": 3,
                "free_throws_attempted": 3,
                "rebounds": 2,
                "assists": 3,
                "steals": 2,
                "blocks": 0,
                "turnovers": 1
            },
            {
                "name": "Marcus Webb",
                "number": 5,
                "age": 29,
                "position": "PG",
                "position_rank": 1,
                "style": "Floor General",
                "season_ft_pct": 78,
                "is_on_court": True,
                "minutes_played": 31,
                "current_stint_minutes": 5.5,
                "fatigue_level": "Normal",
                "current_fouls": 2,
                "field_goals_made": 4,
                "field_goals_attempted": 9,
                "three_pointers_made": 1,
                "three_pointers_attempted": 3,
                "free_throws_made": 3,
                "free_throws_attempted": 4,
                "rebounds": 3,
                "assists": 7,
                "steals": 2,
                "blocks": 0,
                "turnovers": 2
            },
            {
                "name": "DeShawn Price",
                "number": 21,
                "age": 25,
                "position": "SF",
                "position_rank": 1,
                "style": "Slasher",
                "season_ft_pct": 74,
                "is_on_court": True,
                "minutes_played": 26,
                "current_stint_minutes": 4.0,
                "fatigue_level": "Normal",
                "current_fouls": 1,
                "field_goals_made": 5,
                "field_goals_attempted": 9,
                "three_pointers_made": 0,
                "three_pointers_attempted": 1,
                "free_throws_made": 4,
                "free_throws_attempted": 5,
                "rebounds": 4,
                "assists": 2,
                "steals": 1,
                "blocks": 0,
                "turnovers": 1
            },
            {
                "name": "Viktor Borisov",
                "number": 41,
                "age": 31,
                "position": "PF",
                "position_rank": 1,
                "style": "Versatile",
                "season_ft_pct": 69,
                "is_on_court": True,
                "minutes_played": 25,
                "current_stint_minutes": 6.0,
                "fatigue_level": "Normal",
                "current_fouls": 2,
                "field_goals_made": 3,
                "field_goals_attempted": 6,
                "three_pointers_made": 1,
                "three_pointers_attempted": 2,
                "free_throws_made": 2,
                "free_throws_attempted": 3,
                "rebounds": 5,
                "assists": 2,
                "steals": 1,
                "blocks": 1,
                "turnovers": 1
            },
            {
                "name": "Gal Ohayon",
                "number": 55,
                "age": 27,
                "position": "C",
                "position_rank": 1,
                "style": "Rim Protector",
                "season_ft_pct": 52,
                "is_on_court": True,
                "minutes_played": 22,
                "current_stint_minutes": 3.0,
                "fatigue_level": "Normal",
                "current_fouls": 2,
                "field_goals_made": 2,
                "field_goals_attempted": 4,
                "three_pointers_made": 0,
                "three_pointers_attempted": 0,
                "free_throws_made": 1,
                "free_throws_attempted": 2,
                "rebounds": 8,
                "assists": 0,
                "steals": 0,
                "blocks": 3,
                "turnovers": 1
            },
            # ── BENCH ──────────────────────────────────────────────────────────
            {
                "name": "Chris Nolan",
                "number": 14,
                "age": 24,
                "position": "SG",
                "position_rank": 2,
                "style": "Sharpshooter",
                "season_ft_pct": 83,
                "is_on_court": False,
                "minutes_played": 9,
                "current_stint_minutes": 0.0,
                "fatigue_level": "Fresh",
                "current_fouls": 0,
                "field_goals_made": 1,
                "field_goals_attempted": 3,
                "three_pointers_made": 1,
                "three_pointers_attempted": 2,
                "free_throws_made": 0,
                "free_throws_attempted": 0,
                "rebounds": 0,
                "assists": 1,
                "steals": 0,
                "blocks": 0,
                "turnovers": 0
            },
            {
                "name": "Amir Sasi",
                "number": 8,
                "age": 20,
                "position": "C",
                "position_rank": 2,
                "style": "Rim Protector",
                "season_ft_pct": 48,
                "is_on_court": False,
                "minutes_played": 6,
                "current_stint_minutes": 0.0,
                "fatigue_level": "Fresh",
                "current_fouls": 0,
                "field_goals_made": 0,
                "field_goals_attempted": 1,
                "three_pointers_made": 0,
                "three_pointers_attempted": 0,
                "free_throws_made": 0,
                "free_throws_attempted": 0,
                "rebounds": 2,
                "assists": 0,
                "steals": 0,
                "blocks": 1,
                "turnovers": 0
            }
        ]
    }
}
GAME_STATE_EXAMPLE = {
    "venue_type": "Home",
    "target_team": "Home",
    "home_score": 88,
    "away_score": 82,
    "current_period": 4,
    "minutes_remaining": 3,
    "seconds_remaining": 45,
    "possession": "Home",
    "home_timeouts_remaining": 2,
    "away_timeouts_remaining": 1,
    "home_team_fouls": 3,
    "away_team_fouls": 5,

    "rules": {
        "league_format": "FIBA"
    },

    "momentum": {
        "overall_trend": "Strong Home",
        "home_team_run": 8,
        "away_team_run": 0,
        "crowd_intensity": "Electric"
    },

    "directives": {
    "offensive_strategy": "Motion Offense",
    "defensive_focus": "Protect the Paint",
    "risk_tolerance": "High",
    "game_objective": "Win Now"
},

    "home_team": {
        "name": "BGU Lakers",
        "league_position": 1,
        "win_streak": 3,
        "offensive_rank": 2,
        "defensive_rank": 4,
        "upcoming_schedule_density": "High",
        "players": [
            # ── STARTERS (is_on_court: True) ──────────────────────────────────
            {
                "name": "Noam Peretz",
                "number": 7,
                "age": 24,
                "position": "PG",
                "position_rank": 1,
                "style": "Floor General",
                "season_ft_pct": 88,
                "is_on_court": True,
                "minutes_played": 32,
                "current_stint_minutes": 6.5,
                "fatigue_level": "Normal",
                "current_fouls": 2,
                "field_goals_made": 5,
                "field_goals_attempted": 10,
                "three_pointers_made": 2,
                "three_pointers_attempted": 4,
                "free_throws_made": 4,
                "free_throws_attempted": 4,
                "rebounds": 3,
                "assists": 8,
                "steals": 2,
                "blocks": 0,
                "turnovers": 3
            },
            {
                "name": "Lior Cohen",
                "number": 3,
                "age": 22,
                "position": "SG",
                "position_rank": 1,
                "style": "Sharpshooter",
                "season_ft_pct": 85,
                "is_on_court": True,
                "minutes_played": 28,
                "current_stint_minutes": 4.0,
                "fatigue_level": "Normal",
                "current_fouls": 1,
                "field_goals_made": 6,
                "field_goals_attempted": 12,
                "three_pointers_made": 4,
                "three_pointers_attempted": 7,
                "free_throws_made": 2,
                "free_throws_attempted": 2,
                "rebounds": 2,
                "assists": 3,
                "steals": 1,
                "blocks": 0,
                "turnovers": 1
            },
            {
                "name": "Tal Shapira",
                "number": 23,
                "age": 26,
                "position": "SF",
                "position_rank": 1,
                "style": "Slasher",
                "season_ft_pct": 72,
                "is_on_court": True,
                "minutes_played": 30,
                "current_stint_minutes": 5.0,
                "fatigue_level": "Tired",
                "current_fouls": 3,
                "field_goals_made": 7,
                "field_goals_attempted": 13,
                "three_pointers_made": 1,
                "three_pointers_attempted": 3,
                "free_throws_made": 3,
                "free_throws_attempted": 5,
                "rebounds": 5,
                "assists": 2,
                "steals": 1,
                "blocks": 1,
                "turnovers": 2
            },
            {
                "name": "Avi Mizrahi",
                "number": 15,
                "age": 28,
                "position": "PF",
                "position_rank": 1,
                "style": "Post Threat",
                "season_ft_pct": 65,
                "is_on_court": True,
                "minutes_played": 29,
                "current_stint_minutes": 7.0,
                "fatigue_level": "Exhausted",
                "current_fouls": 2,
                "field_goals_made": 4,
                "field_goals_attempted": 7,
                "three_pointers_made": 0,
                "three_pointers_attempted": 0,
                "free_throws_made": 2,
                "free_throws_attempted": 4,
                "rebounds": 9,
                "assists": 1,
                "steals": 0,
                "blocks": 2,
                "turnovers": 2
            },
            {
                "name": "Ronen Bar",
                "number": 11,
                "age": 30,
                "position": "C",
                "position_rank": 1,
                "style": "Rim Protector",
                "season_ft_pct": 58,
                "is_on_court": True,
                "minutes_played": 27,
                "current_stint_minutes": 3.5,
                "fatigue_level": "Normal",
                "current_fouls": 4,
                "field_goals_made": 3,
                "field_goals_attempted": 5,
                "three_pointers_made": 0,
                "three_pointers_attempted": 0,
                "free_throws_made": 1,
                "free_throws_attempted": 2,
                "rebounds": 10,
                "assists": 1,
                "steals": 0,
                "blocks": 4,
                "turnovers": 1
            },
            # ── BENCH ─────────────────────────────────────────────────────────
            {
                "name": "Yoni Katz",
                "number": 9,
                "age": 21,
                "position": "PG",
                "position_rank": 2,
                "style": "Versatile",
                "season_ft_pct": 80,
                "is_on_court": False,
                "minutes_played": 10,
                "current_stint_minutes": 0.0,
                "fatigue_level": "Fresh",
                "current_fouls": 0,
                "field_goals_made": 1,
                "field_goals_attempted": 3,
                "three_pointers_made": 1,
                "three_pointers_attempted": 2,
                "free_throws_made": 0,
                "free_throws_attempted": 0,
                "rebounds": 1,
                "assists": 2,
                "steals": 1,
                "blocks": 0,
                "turnovers": 1
            },
            {
                "name": "Dor Eliyahu",
                "number": 22,
                "age": 23,
                "position": "PF",
                "position_rank": 2,
                "style": "Wing Defender",
                "season_ft_pct": 70,
                "is_on_court": False,
                "minutes_played": 12,
                "current_stint_minutes": 0.0,
                "fatigue_level": "Fresh",
                "current_fouls": 1,
                "field_goals_made": 2,
                "field_goals_attempted": 4,
                "three_pointers_made": 0,
                "three_pointers_attempted": 1,
                "free_throws_made": 1,
                "free_throws_attempted": 2,
                "rebounds": 4,
                "assists": 0,
                "steals": 1,
                "blocks": 1,
                "turnovers": 0
            },
            {
                "name": "Moshe Avraham",
                "number": 44,
                "age": 32,
                "position": "C",
                "position_rank": 2,
                "style": "Post Threat",
                "season_ft_pct": 55,
                "is_on_court": False,
                "minutes_played": 8,
                "current_stint_minutes": 0.0,
                "fatigue_level": "Fresh",
                "current_fouls": 0,
                "field_goals_made": 1,
                "field_goals_attempted": 2,
                "three_pointers_made": 0,
                "three_pointers_attempted": 0,
                "free_throws_made": 0,
                "free_throws_attempted": 1,
                "rebounds": 3,
                "assists": 0,
                "steals": 0,
                "blocks": 1,
                "turnovers": 1
            }
        ]
    },

    "away_team": {
        "name": "Tel Aviv Sharks",
        "league_position": 3,
        "win_streak": -1,
        "offensive_rank": 5,
        "defensive_rank": 2,
        "upcoming_schedule_density": "Medium",
        "players": [
            # ── STARTERS (is_on_court: True) ──────────────────────────────────
            {
                "name": "John Doe",
                "number": 30,
                "age": 26,
                "position": "SG",
                "position_rank": 1,
                "style": "Sharpshooter",
                "season_ft_pct": 92,
                "is_on_court": True,
                "minutes_played": 34,
                "current_stint_minutes": 8.0,
                "fatigue_level": "Tired",
                "current_fouls": 4,
                "field_goals_made": 8,
                "field_goals_attempted": 15,
                "three_pointers_made": 4,
                "three_pointers_attempted": 8,
                "free_throws_made": 2,
                "free_throws_attempted": 2,
                "rebounds": 2,
                "assists": 4,
                "steals": 1,
                "blocks": 0,
                "turnovers": 2
            },
            {
                "name": "Marcus Webb",
                "number": 5,
                "age": 29,
                "position": "PG",
                "position_rank": 1,
                "style": "Floor General",
                "season_ft_pct": 78,
                "is_on_court": True,
                "minutes_played": 31,
                "current_stint_minutes": 5.5,
                "fatigue_level": "Normal",
                "current_fouls": 2,
                "field_goals_made": 4,
                "field_goals_attempted": 9,
                "three_pointers_made": 1,
                "three_pointers_attempted": 3,
                "free_throws_made": 3,
                "free_throws_attempted": 4,
                "rebounds": 3,
                "assists": 7,
                "steals": 2,
                "blocks": 0,
                "turnovers": 3
            },
            {
                "name": "DeShawn Price",
                "number": 21,
                "age": 25,
                "position": "SF",
                "position_rank": 1,
                "style": "Slasher",
                "season_ft_pct": 74,
                "is_on_court": True,
                "minutes_played": 26,
                "current_stint_minutes": 4.0,
                "fatigue_level": "Normal",
                "current_fouls": 1,
                "field_goals_made": 5,
                "field_goals_attempted": 10,
                "three_pointers_made": 0,
                "three_pointers_attempted": 2,
                "free_throws_made": 4,
                "free_throws_attempted": 6,
                "rebounds": 4,
                "assists": 1,
                "steals": 0,
                "blocks": 0,
                "turnovers": 2
            },
            {
                "name": "Viktor Borisov",
                "number": 41,
                "age": 31,
                "position": "PF",
                "position_rank": 1,
                "style": "Versatile",
                "season_ft_pct": 69,
                "is_on_court": True,
                "minutes_played": 25,
                "current_stint_minutes": 6.0,
                "fatigue_level": "Normal",
                "current_fouls": 3,
                "field_goals_made": 3,
                "field_goals_attempted": 6,
                "three_pointers_made": 1,
                "three_pointers_attempted": 2,
                "free_throws_made": 1,
                "free_throws_attempted": 2,
                "rebounds": 6,
                "assists": 2,
                "steals": 1,
                "blocks": 1,
                "turnovers": 1
            },
            {
                "name": "Gal Ohayon",
                "number": 55,
                "age": 27,
                "position": "C",
                "position_rank": 1,
                "style": "Rim Protector",
                "season_ft_pct": 52,
                "is_on_court": True,
                "minutes_played": 22,
                "current_stint_minutes": 3.0,
                "fatigue_level": "Normal",
                "current_fouls": 2,
                "field_goals_made": 2,
                "field_goals_attempted": 4,
                "three_pointers_made": 0,
                "three_pointers_attempted": 0,
                "free_throws_made": 0,
                "free_throws_attempted": 1,
                "rebounds": 8,
                "assists": 0,
                "steals": 0,
                "blocks": 3,
                "turnovers": 1
            },
            # ── BENCH ─────────────────────────────────────────────────────────
            {
                "name": "Chris Nolan",
                "number": 14,
                "age": 24,
                "position": "SG",
                "position_rank": 2,
                "style": "Sharpshooter",
                "season_ft_pct": 83,
                "is_on_court": False,
                "minutes_played": 9,
                "current_stint_minutes": 0.0,
                "fatigue_level": "Fresh",
                "current_fouls": 0,
                "field_goals_made": 1,
                "field_goals_attempted": 3,
                "three_pointers_made": 1,
                "three_pointers_attempted": 2,
                "free_throws_made": 0,
                "free_throws_attempted": 0,
                "rebounds": 0,
                "assists": 1,
                "steals": 0,
                "blocks": 0,
                "turnovers": 0
            },
            {
                "name": "Amir Sasi",
                "number": 8,
                "age": 20,
                "position": "C",
                "position_rank": 2,
                "style": "Rim Protector",
                "season_ft_pct": 48,
                "is_on_court": False,
                "minutes_played": 6,
                "current_stint_minutes": 0.0,
                "fatigue_level": "Fresh",
                "current_fouls": 0,
                "field_goals_made": 0,
                "field_goals_attempted": 1,
                "three_pointers_made": 0,
                "three_pointers_attempted": 0,
                "free_throws_made": 0,
                "free_throws_attempted": 0,
                "rebounds": 2,
                "assists": 0,
                "steals": 0,
                "blocks": 1,
                "turnovers": 0
            }
        ]
    }
}


ANALYSIS_REPORT_EXAMPLE = {
    "summary": (
        "BGU Lakers lead by 6 in CLUTCH TIME with 3:45 remaining. "
        "Momentum is strongly in our favor on an 8 point run, but our center "
        "is one foul from disqualification and a key player is exhausted."
    ),
    "main_threat": (
        "Ronen Bar (#11) has Fouls:4/5 — one more foul removes our primary "
        "rim protector in the most critical minutes of the game."
    ),
    "recommended_actions": [
        {
            "reasoning": (
                "Per [STRATEGIC CONTEXT], Risk Tolerance is High — Rank:1 stars stay on court "
                "unless Injured. However [ACTIONABLE ALERTS] flags Avi Mizrahi (#15) as Exhausted "
                "(Fouls:2/5, Rank:1), which crosses the threshold even at High risk. "
                "Dor Eliyahu (#22, PF, Fresh) is available in [AVAILABLE BENCH PERSONNEL] "
                "to restore defensive energy for the final 3 minutes of CLUTCH TIME."
            ),
            "action_type": "Substitution",
            "description": "Sub out #15, bring in #22.",
            "expected_impact": "Restores defensive intensity at PF without disrupting positional structure.",
            "priority": "High",
            "involved_player_numbers": [15, 22]
        },
        {
            "reasoning": (
                "[ACTIONABLE ALERTS] shows the opponent is in PENALTY (5 team fouls). "
                "Attacking the paint forces free throws and burns clock — "
                "both critical with a 6-point lead in CLUTCH TIME."
            ),
            "action_type": "Offensive Focus Shift",
            "description": "Attack the paint every possession to draw fouls.",
            "expected_impact": "Forces opponent into more fouls, earns free throws, slows the game.",
            "priority": "High",
            "involved_player_numbers": []
        },
        {
            "reasoning": (
                "John Doe (#30) appears in [OPPONENT THREAT ON COURT] with EFF:18 and Fouls:4/5. "
                "One more foul disqualifies him. Running pick-and-roll actions directly at him "
                "forces defensive effort and increases foul risk without requiring a substitution."
            ),
            "action_type": "Foul Strategy",
            "description": "Direct pick-and-roll actions toward #30 every possession.",
            "expected_impact": "Forces his 5th foul and removes the opponent's primary scorer.",
            "priority": "Medium",
            "involved_player_numbers": [30]
        },
        {
            "reasoning": (
                "Per [GAME CONTEXT], only 2 timeouts remain with 3:45 left. "
                "Running the full shot clock reduces opponent possession count "
                "and preserves a timeout for a critical late-game stop."
            ),
            "action_type": "Pace Management",
            "description": "Run the full shot clock on every possession.",
            "expected_impact": "Limits opponent comeback opportunities and saves timeout for critical moment.",
            "priority": "Medium",
            "involved_player_numbers": []
        }
    ],
    "risk_assessment": (
        "Keeping Ronen Bar (#11) on court with Fouls:4/5 is a calculated gamble under High risk tolerance. "
        "If he fouls out we lose our primary rim protector with no equivalent C on the bench. "
        "The substitution of #15 mitigates fatigue risk without touching the star lineup. "
        "Confidence is high because alerts are unambiguous and bench options match the situation."
    ),
    "confidence_score": 0.91
}
LOW_CONFIDENCE_EXAMPLE = {
    # ── Scenario: CLUTCH TIME, losing, terrible bench, conflicting directives ─
    # Designed to create maximum AI uncertainty:
    # - Must sub exhausted star (Low risk tolerance) but only bench player
    #   is also tired with fouls and terrible FT% (conflicts Kill the Clock)
    # - Star in foul trouble but can't be rested (no good replacement)
    # - Conflicting directives: Kill the Clock needs high FT%, but we're losing
    # Expected: confidence 0.45-0.60, self_critique populated, retry triggered

    "venue_type": "Away",
    "target_team": "Home",
    "home_score": 71,
    "away_score": 76,
    "current_period": 4,
    "minutes_remaining": 1,
    "seconds_remaining": 20,
    "possession": "Away",
    "home_timeouts_remaining": 1,
    "away_timeouts_remaining": 2,
    "home_team_fouls": 4,
    "away_team_fouls": 2,

    "rules": {"league_format": "FIBA"},

    "momentum": {
        "overall_trend": "Strong Away",
        "home_team_run": 0,
        "away_team_run": 8,
        "crowd_intensity": "Hostile"
    },

    # ── Conflicting directives — Kill the Clock when losing = contradiction ──
    # Kill the Clock needs high FT% players but we're down 5 with 80 seconds left
    # Low risk tolerance forces subbing exhausted players
    # But the only bench player has terrible FT% and is also tired
    "directives": {
        "offensive_strategy": "Attack the Paint",
        "defensive_focus": "Protect the Paint",
        "risk_tolerance": "Low",
        "game_objective": "Kill the Clock"
    },

    "home_team": {
        "name": "BGU Lakers",
        "league_position": 1,
        "win_streak": -2,
        "offensive_rank": 2,
        "defensive_rank": 4,
        "upcoming_schedule_density": "High",
        "players": [
            # ── STARTERS — all in some kind of trouble ────────────────────────
            {
                "name": "Noam Peretz",
                "number": 7,
                "age": 24,
                "position": "PG",
                "position_rank": 1,
                "style": "Floor General",
                "season_ft_pct": 88,
                "is_on_court": True,
                "minutes_played": 37,
                "current_stint_minutes": 9.0,
                "fatigue_level": "Tired",
                "current_fouls": 4,  # one from fouling out
                "field_goals_made": 3,
                "field_goals_attempted": 10,
                "three_pointers_made": 1,
                "three_pointers_attempted": 4,
                "free_throws_made": 2,
                "free_throws_attempted": 2,
                "rebounds": 2,
                "assists": 4,
                "steals": 1,
                "blocks": 0,
                "turnovers": 3
            },
            {
                "name": "Lior Cohen",
                "number": 3,
                "age": 22,
                "position": "SG",
                "position_rank": 1,
                "style": "Sharpshooter",
                "season_ft_pct": 85,
                "is_on_court": True,
                "minutes_played": 35,
                "current_stint_minutes": 7.0,
                "fatigue_level": "Normal",
                "current_fouls": 2,
                "field_goals_made": 4,
                "field_goals_attempted": 11,
                "three_pointers_made": 2,
                "three_pointers_attempted": 6,
                "free_throws_made": 1,
                "free_throws_attempted": 1,
                "rebounds": 1,
                "assists": 2,
                "steals": 1,
                "blocks": 0,
                "turnovers": 2
            },
            {
                "name": "Tal Shapira",
                "number": 23,
                "age": 26,
                "position": "SF",
                "position_rank": 1,
                "style": "Slasher",
                "season_ft_pct": 72,
                "is_on_court": True,
                "minutes_played": 36,
                "current_stint_minutes": 8.0,
                "fatigue_level": "Exhausted",  # must be subbed — Low risk tolerance
                "current_fouls": 3,
                "field_goals_made": 3,
                "field_goals_attempted": 9,
                "three_pointers_made": 0,
                "three_pointers_attempted": 2,
                "free_throws_made": 1,
                "free_throws_attempted": 3,
                "rebounds": 3,
                "assists": 1,
                "steals": 0,
                "blocks": 0,
                "turnovers": 2
            },
            {
                "name": "Avi Mizrahi",
                "number": 15,
                "age": 28,
                "position": "PF",
                "position_rank": 1,
                "style": "Post Threat",
                "season_ft_pct": 65,
                "is_on_court": True,
                "minutes_played": 34,
                "current_stint_minutes": 6.0,
                "fatigue_level": "Normal",
                "current_fouls": 2,
                "field_goals_made": 4,
                "field_goals_attempted": 7,
                "three_pointers_made": 0,
                "three_pointers_attempted": 0,
                "free_throws_made": 2,
                "free_throws_attempted": 4,
                "rebounds": 7,
                "assists": 1,
                "steals": 0,
                "blocks": 2,
                "turnovers": 1
            },
            {
                "name": "Ronen Bar",
                "number": 11,
                "age": 30,
                "position": "C",
                "position_rank": 1,
                "style": "Rim Protector",
                "season_ft_pct": 58,
                "is_on_court": True,
                "minutes_played": 33,
                "current_stint_minutes": 5.0,
                "fatigue_level": "Normal",
                "current_fouls": 4,  # also one from fouling out
                "field_goals_made": 2,
                "field_goals_attempted": 4,
                "three_pointers_made": 0,
                "three_pointers_attempted": 0,
                "free_throws_made": 1,
                "free_throws_attempted": 3,
                "rebounds": 8,
                "assists": 0,
                "steals": 0,
                "blocks": 3,
                "turnovers": 1
            },
            # ── BENCH — only ONE player available, and they're bad ────────────
            # This is the core of the low confidence scenario:
            # Kill the Clock needs high FT% but this player has 42%
            # Low risk tolerance says sub Tal Shapira but replacement is terrible
            # AI must make a bad choice and knows it
            {
                "name": "Yoni Katz",
                "number": 9,
                "age": 21,
                "position": "PG",   # wrong position for SF (Tal Shapira)
                "position_rank": 2,
                "style": "Versatile",
                "season_ft_pct": 42,  # terrible — Kill the Clock liability
                "is_on_court": False,
                "minutes_played": 8,
                "current_stint_minutes": 0.0,
                "fatigue_level": "Normal",
                "current_fouls": 2,
                "field_goals_made": 0,
                "field_goals_attempted": 4,
                "three_pointers_made": 0,
                "three_pointers_attempted": 2,
                "free_throws_made": 1,
                "free_throws_attempted": 4,
                "rebounds": 0,
                "assists": 1,
                "steals": 0,
                "blocks": 0,
                "turnovers": 2
            }
        ]
    },

    "away_team": {
        "name": "Tel Aviv Sharks",
        "league_position": 3,
        "win_streak": 4,
        "offensive_rank": 5,
        "defensive_rank": 2,
        "upcoming_schedule_density": "Medium",
        "players": [
            {
                "name": "John Doe",
                "number": 30,
                "age": 26,
                "position": "SG",
                "position_rank": 1,
                "style": "Sharpshooter",
                "season_ft_pct": 92,
                "is_on_court": True,
                "minutes_played": 36,
                "current_stint_minutes": 8.0,
                "fatigue_level": "Normal",
                "current_fouls": 1,
                "field_goals_made": 8,
                "field_goals_attempted": 14,
                "three_pointers_made": 4,
                "three_pointers_attempted": 7,
                "free_throws_made": 4,
                "free_throws_attempted": 4,
                "rebounds": 2,
                "assists": 3,
                "steals": 2,
                "blocks": 0,
                "turnovers": 1
            },
            {
                "name": "Marcus Webb",
                "number": 5,
                "age": 29,
                "position": "PG",
                "position_rank": 1,
                "style": "Floor General",
                "season_ft_pct": 78,
                "is_on_court": True,
                "minutes_played": 34,
                "current_stint_minutes": 6.0,
                "fatigue_level": "Normal",
                "current_fouls": 1,
                "field_goals_made": 3,
                "field_goals_attempted": 7,
                "three_pointers_made": 1,
                "three_pointers_attempted": 3,
                "free_throws_made": 2,
                "free_throws_attempted": 3,
                "rebounds": 3,
                "assists": 6,
                "steals": 1,
                "blocks": 0,
                "turnovers": 2
            },
            {
                "name": "DeShawn Price",
                "number": 21,
                "age": 25,
                "position": "SF",
                "position_rank": 1,
                "style": "Slasher",
                "season_ft_pct": 74,
                "is_on_court": True,
                "minutes_played": 30,
                "current_stint_minutes": 5.0,
                "fatigue_level": "Normal",
                "current_fouls": 2,
                "field_goals_made": 3,
                "field_goals_attempted": 6,
                "three_pointers_made": 0,
                "three_pointers_attempted": 1,
                "free_throws_made": 3,
                "free_throws_attempted": 4,
                "rebounds": 3,
                "assists": 1,
                "steals": 1,
                "blocks": 0,
                "turnovers": 1
            },
            {
                "name": "Viktor Borisov",
                "number": 41,
                "age": 31,
                "position": "PF",
                "position_rank": 1,
                "style": "Versatile",
                "season_ft_pct": 69,
                "is_on_court": True,
                "minutes_played": 28,
                "current_stint_minutes": 4.0,
                "fatigue_level": "Normal",
                "current_fouls": 2,
                "field_goals_made": 2,
                "field_goals_attempted": 5,
                "three_pointers_made": 1,
                "three_pointers_attempted": 2,
                "free_throws_made": 1,
                "free_throws_attempted": 2,
                "rebounds": 4,
                "assists": 2,
                "steals": 0,
                "blocks": 1,
                "turnovers": 1
            },
            {
                "name": "Gal Ohayon",
                "number": 55,
                "age": 27,
                "position": "C",
                "position_rank": 1,
                "style": "Rim Protector",
                "season_ft_pct": 52,
                "is_on_court": True,
                "minutes_played": 25,
                "current_stint_minutes": 3.0,
                "fatigue_level": "Normal",
                "current_fouls": 1,
                "field_goals_made": 2,
                "field_goals_attempted": 4,
                "three_pointers_made": 0,
                "three_pointers_attempted": 0,
                "free_throws_made": 1,
                "free_throws_attempted": 2,
                "rebounds": 6,
                "assists": 0,
                "steals": 0,
                "blocks": 2,
                "turnovers": 1
            },
            {
                "name": "Chris Nolan",
                "number": 14,
                "age": 24,
                "position": "SG",
                "position_rank": 2,
                "style": "Sharpshooter",
                "season_ft_pct": 83,
                "is_on_court": False,
                "minutes_played": 9,
                "current_stint_minutes": 0.0,
                "fatigue_level": "Fresh",
                "current_fouls": 0,
                "field_goals_made": 1,
                "field_goals_attempted": 2,
                "three_pointers_made": 1,
                "three_pointers_attempted": 2,
                "free_throws_made": 0,
                "free_throws_attempted": 0,
                "rebounds": 0,
                "assists": 0,
                "steals": 0,
                "blocks": 0,
                "turnovers": 0
            },
            {
                "name": "Amir Sasi",
                "number": 8,
                "age": 20,
                "position": "C",
                "position_rank": 2,
                "style": "Rim Protector",
                "season_ft_pct": 48,
                "is_on_court": False,
                "minutes_played": 6,
                "current_stint_minutes": 0.0,
                "fatigue_level": "Fresh",
                "current_fouls": 0,
                "field_goals_made": 0,
                "field_goals_attempted": 1,
                "three_pointers_made": 0,
                "three_pointers_attempted": 0,
                "free_throws_made": 0,
                "free_throws_attempted": 0,
                "rebounds": 2,
                "assists": 0,
                "steals": 0,
                "blocks": 1,
                "turnovers": 0
            }
        ]
    }
}